@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMUpEOTM2QVhTRE5NUTcxM1A1WE1WUlFEViIsIm5iZiI6MTc3MjYwOTMzOCwiZXhwIjoxNzcyODI1MzM4LCJpYXQiOjE3NzI2MDkzMzh9.DNowroywot0E-WkSjsOpLDPJviZoY4MpPSl2OlZBj4A
### Login
POST {{baseUrl}}/api/v1/users/login
Content-Type: application/json
Accept: application/json

{
    "identifier": "chloe.kim",
    "password": "Admin@123"
}

### Get users where lastName like kim
GET {{baseUrl}}/api/v1/users?pageSize=10&filter[lastName][$containsi]=kim
Accept: application/json
Authorization: Bearer {{token}}

### Get users, gen z and gender is female
GET {{baseUrl}}/api/v1/users?pageSize=10&filter[$and][0][gender][$in][0]=2&filter[$and][1][dateOfBirth][$between][0]=1997-01-01&filter[$and][1][dateOfBirth][$between][1]=2012-12-31&sort=firstName, lastName:desc
Accept: application/json
Authorization: Bearer {{token}}

### Get users, gen z and gender is female
GET {{baseUrl}}/api/v1/users?pageSize=10&keyword=kr&targets=email
Accept: application/json
Authorization: Bearer {{token}}

### Get users, gen z and gender is female
GET {{baseUrl}}/api/v1/users?page=1&pageSize=100&keyword=01KEEMMJBCZGJ53C3NRQAPQC1B&targets=id&targets=PhoneNumber&sort=createdAt:desc,id&page=1&pageSize=10
Accept: application/json
Authorization: Bearer {{token}}